apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nodeapp1
  name: nodeapp1
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: nodeapp1
status:
  loadBalancer: {}